apiVersion: v1
kind: Service
metadata:
  name: watchtower-server
  namespace: watchtower-staging
  labels:
    app.kubernetes.io/name: watchtower
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app: watchtower-server
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
