apiVersion: v1
kind: Service
metadata:
  name: watchtower-client
  namespace: watchtower-staging
  labels:
    app.kubernetes.io/name: watchtower
    app.kubernetes.io/component: client
spec:
  type: ClusterIP
  selector:
    app: watchtower-client
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
